# Sentio AI 邮件伙伴系统配置文件
# 这是默认配置，生产环境中应通过环境变量覆盖敏感信息

[database]
url = "mongodb://localhost:27017/sentio"
max_connections = 10
connect_timeout = 30

[email.imap]
host = "imap.gmail.com"
port = 993
username = "your-email@example.com"
password = "your-app-password"
use_tls = true

[email.smtp]
host = "smtp.gmail.com"
port = 587
username = "your-email@example.com"
password = "your-app-password"
use_tls = true

[llm]
provider = "deepseek"
api_key = "your-deepseek-api-key"
base_url = "https://api.deepseek.com"
model = "deepseek-chat"
timeout = 120
max_retries = 3

[telemetry]
log_level = "info"
console = true
# log_file = "/var/log/sentio/app.log"  # 可选：日志文件路径
json_format = false

[server]
host = "127.0.0.1"
port = 8080
workers = 4
