# Sentio Configuration File
# Copy this file to sentio.toml and adjust the values

[email]
# Only process emails from this sender
allowed_sender = "1607033217@qq.com"

[email.smtp]
host = "smtp.gmail.com"
port = 587
username = "your-email@example.com"
password = "your-app-password"
use_tls = true

[llm]
provider = "deepseek"
api_key = "your-deepseek-api-key"
base_url = "https://api.deepseek.com/v1"
model = "deepseek-chat"
timeout = 120
max_retries = 3

[telemetry]
log_level = "info"
console = true
# log_file = "sentio.log"  # Optional: enable file logging

[server]
host = "127.0.0.1"
port = 8080
workers = 4