[package]
name = "sentio_telemetry"
version = "0.1.0"
edition = "2021"

[dependencies]
shared_logic = { path = "../shared_logic" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
