# Sentio AI 邮件助手默认配置文件
# 这个文件包含了所有服务的默认配置，可以通过环境变量覆盖

[email.smtp]
host = "smtp.example.com"
port = 587
username = "your-email@example.com"
password = "your-app-password"
use_tls = true

[llm]
provider = "deepseek"
api_key = "your-deepseek-api-key"
base_url = "https://api.deepseek.com"
model = "deepseek-chat"
timeout = 120
max_retries = 3

[telemetry]
log_level = "info"
console = true
json_format = false
log_file = "app.log"

[server]
host = "127.0.0.1"
port = 8080
workers = 4

[database]
max_connections = 10