[package]
name = "shared_logic"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
config = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }

[features]
default = []
